version: "3.9"
services:
  usuario:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: delivery-usuario
    restart: unless-stopped
    ports:
      - "9525:9525" # Porta pública do microsserviço de Usuário
    environment:
      PORT: 9525
      NODE_ENV: production
      JWT_EXPIRES_IN: 7d
      BCRYPT_ROUNDS: 10
      INFISICAL_CLIENT_ID: ""
      INFISICAL_CLIENT_SECRET: ""
      INFISICAL_PROJECT_ID: ""
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
